"""Regenerate the root README.md: the single central landing page.

The institution and course listings come entirely from resources/; a
maintainer's normal README.md first paragraph is what feeds the blurb here
(see model._first_paragraph), so writing a normal README is enough to also
feed the index.
"""
from __future__ import annotations

from pathlib import Path

import click

from . import model as m
from .scorecard import TIER_BADGE, tier_for

HEADER = """# RVI Education Central

A central home for RISC-V lecture and lab material, shared and reused across
universities, institutions, and companies. Material lives under `resources/`,
one directory per contributing institution; shareable figures are pooled by
topic under `common/`. See [`CONTRIBUTING.md`](CONTRIBUTING.md) to add your own material.

This file, including the institution listing below, is generated by
`_tools/gen_readme.py` from the descriptors under `resources/` - edit those,
NOT this file.

## Core ideas

- One shared home for RISC-V teaching material, so universities and companies can reuse each other's lectures and labs instead of each building the same thing from scratch.
- Every contributor keeps their own space: one folder per institution, and material can be added in whatever format you already teach with.
- Figures and diagrams are gathered by topic, so anyone can pull a good illustration (a CPU pipeline, a memory layout) straight into their own slides.
- Material is openly licensed by default, which is what makes that reuse legal; you can opt out and just host without sharing.
- Getting listed takes only a few minutes, and going further (documentation, licensing, pooled figures) earns a higher badge on a public scorecard, but is never required.
- The catalog you see below is generated automatically from what contributors add, so it stays current on its own.
"""


def render(root: Path, repo: m.RepoModel) -> str:
    lines = [HEADER, "## Institutions", ""]

    if not repo.resources:
        lines.append("_No institutions have contributed material yet. Be the first — see `CONTRIBUTING.md`._")
        lines.append("")

    for resource in sorted(repo.resources, key=lambda r: r.slug):
        institution = repo.institutions.get(resource.slug)
        name = institution.name if institution else resource.slug
        country = f" ({institution.country})" if institution and institution.country else ""
        homepage = institution.homepage if institution else None
        title = f"[{name}]({homepage})" if homepage else name
        emoji = TIER_BADGE[tier_for(root, resource, repo.institutions)].split(" ", 1)[0]
        heading = f"### {title}{country} [{emoji}](STANDARDS.md)"
        lines.append(heading)
        lines.append("")
        if resource.readme_summary:
            lines.append(resource.readme_summary)
            lines.append("")
        if resource.courses:
            lines.append("| Course | Languages | Level | Topics |")
            lines.append("|---|---|---|---|")
            for course in sorted(resource.courses, key=lambda c: c.slug):
                langs = ", ".join(course.languages) or "-"
                topics = ", ".join(course.topics) or "-"
                title = course.title or course.slug
                # The name links to the in-repo path. For a submodule that path is a gitlink
                # (it 404s on GitHub and for anyone who cloned without the submodule), so we
                # also append a compact link to the upstream repo pinned at the vendored
                # commit when it resolves. Both are shown so it's clear which is which.
                link = f"[{title}]({course.path.as_posix()})"
                if course.submodule_url:
                    link += f" ([upstream ↗]({course.submodule_url}))"
                lines.append(f"| {link} | {langs} | {course.level or '-'} | {topics} |")
            lines.append("")

    lines.append("## Shared asset pool")
    lines.append("")
    lines.append(
        "Figures and diagrams contributed under an open license are pooled by topic under "
        "[`common/`](common/); browse a topic's `README.md` for a gallery, for example "
        "[`common/cpu`](common/cpu)."
    )
    lines.append("")
    lines.append("See [`STANDARDS.md`](STANDARDS.md) for the per-institution compliance scorecard.")
    lines.append("")

    return "\n".join(lines) + "\n"


def build(root: Path) -> None:
    repo = m.load(root)
    (root / "README.md").write_text(render(root, repo), encoding="utf-8")


@click.command()
@click.argument("root", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
def main(root: Path) -> None:
    build(m.find_repo_root(root))
    click.echo("README.md regenerated")


if __name__ == "__main__":
    main()
