"""Regenerate the common/ symlink pool and its per-topic galleries.

common/ is entirely derived from the model: every run wipes and rebuilds it,
so the only way to change its contents is to change a descriptor or asset
under resources/ and re-run. See PLAN.md section 5.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import click

from . import model as m

IMG_EXTS = {".svg", ".png", ".jpg", ".jpeg", ".gif", ".webp"}
_OWNER_REPO_RE = re.compile(r"[:/](?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?/?$")


def _namespaced_name(institution_slug: str, original_name: str, used: set[str]) -> str:
    candidate = f"{institution_slug}__{original_name}"
    if candidate not in used:
        return candidate
    stem, suffix = Path(original_name).stem, Path(original_name).suffix
    n = 2
    while True:
        candidate = f"{institution_slug}__{stem}-{n}{suffix}"
        if candidate not in used:
            return candidate
        n += 1


def _submodule_owner_repo(url: str) -> tuple[str, str] | None:
    match = _OWNER_REPO_RE.search(url)
    return (match.group("owner"), match.group("repo")) if match else None


def _submodule_commit(root: Path, submodule_path: str) -> str | None:
    """The commit SHA the parent repo has pinned for a submodule, from the committed tree."""
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "ls-tree", "HEAD", "--", submodule_path],
            capture_output=True, text=True, check=True, timeout=10,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
        return None
    fields = out.split()
    return fields[2] if len(fields) >= 3 and fields[1] == "commit" else None


def _raw_url(root: Path, gitmodules: dict[str, str], course: m.Course, asset: m.Asset) -> str | None:
    url = gitmodules.get(course.path.as_posix())
    if not url:
        return None
    owner_repo = _submodule_owner_repo(url)
    sha = _submodule_commit(root, course.path.as_posix())
    if not owner_repo or not sha:
        return None
    owner, repo = owner_repo
    rel_within_submodule = Path(*asset.path.parts[len(course.path.parts):]).as_posix()
    return f"https://raw.githubusercontent.com/{owner}/{repo}/{sha}/{rel_within_submodule}"


def _external_for_topic(repo: m.RepoModel, topic: str) -> list[tuple[m.ExternalAsset, m.Course]]:
    return [
        (ea, course)
        for resource in repo.resources
        for course in resource.courses
        for ea in course.external_assets
        if ea.topic == topic
    ]


def _write_gallery(
    topic_dir: Path,
    topic: str,
    topic_meta: dict,
    entries: list[tuple[str, m.Asset, m.Course]],
    repo: m.RepoModel,
) -> None:
    lines = [
        f"# {topic_meta.get('label', topic)}",
        "",
        topic_meta.get("description", ""),
        "",
        "<!-- generated by tools/build_common.py; do not edit by hand -->",
        "",
        "| Preview | Title | Institution | Language | License |",
        "|---|---|---|---|---|",
    ]

    for name, asset, course in entries:
        institution = repo.institutions.get(asset.resource_slug)
        inst_name = institution.name if institution else asset.resource_slug
        title = asset.title or Path(asset.path).stem
        lang = asset.lang or "-"
        preview = ""
        if Path(name).suffix.lower() in IMG_EXTS:
            if asset.from_submodule:
                url = _raw_url(repo.root, repo.gitmodules, course, asset)
                preview = f"![{title}]({url})" if url else "_submodule asset, not yet pinned_"
            else:
                # Link straight to the file under resources/, not the common/ symlink:
                # GitHub's web UI and raw content serving don't dereference symlinks, so an
                # image tag pointing at the symlink itself renders as broken.
                real_path = os.path.relpath(repo.root / asset.path, start=topic_dir)
                preview = f"![{title}]({real_path})"
        lines.append(f"| {preview} | {title} | {inst_name} | {lang} | {asset.license} |")

    for ea, course in _external_for_topic(repo, topic):
        institution = repo.institutions.get(course.resource_slug)
        inst_name = institution.name if institution else course.resource_slug
        lines.append(f"| [external link]({ea.url}) | {ea.title} | {inst_name} | {ea.lang or '-'} | {ea.license} |")

    (topic_dir / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def build(root: Path) -> None:
    repo = m.load(root)
    if repo.errors:
        raise SystemExit(
            "refusing to rebuild common/: the repository model has errors; "
            "run `python -m tools.validate .` first"
        )

    common_dir = root / "common"
    if common_dir.exists():
        for path in common_dir.rglob("*"):
            if path.is_file() and not path.is_symlink() and path.name != "README.md":
                raise SystemExit(f"{path.relative_to(root)} is not a symlink or generated README; refusing to wipe common/")
        shutil.rmtree(common_dir)
    common_dir.mkdir(parents=True)

    assets_with_course = [
        (asset, course)
        for resource in repo.resources
        for course in resource.courses
        for asset in course.assets
        if asset.pooled
    ]
    # Deterministic iteration: same input always produces the same tree and the same diff.
    assets_with_course.sort(key=lambda ac: (ac[0].topic, ac[0].resource_slug, ac[0].path.as_posix()))

    by_topic: dict[str, list[tuple[str, m.Asset, m.Course]]] = {}
    used_names: dict[str, set[str]] = {}

    for asset, course in assets_with_course:
        topic_dir = common_dir / asset.topic
        topic_dir.mkdir(parents=True, exist_ok=True)
        used = used_names.setdefault(asset.topic, set())
        name = _namespaced_name(asset.resource_slug, asset.path.name, used)
        used.add(name)
        target = os.path.relpath(root / asset.path, start=topic_dir)
        (topic_dir / name).symlink_to(target)
        by_topic.setdefault(asset.topic, []).append((name, asset, course))

    topics_with_content = set(by_topic) | {
        topic for topic in repo.topics if _external_for_topic(repo, topic)
    }
    for topic in sorted(topics_with_content):
        topic_dir = common_dir / topic
        topic_dir.mkdir(parents=True, exist_ok=True)
        _write_gallery(topic_dir, topic, repo.topics[topic], by_topic.get(topic, []), repo)


@click.command()
@click.argument("root", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
def main(root: Path) -> None:
    build(m.find_repo_root(root))
    click.echo("common/ rebuilt")


if __name__ == "__main__":
    main()
