"""Compute the compliance scorecard: STANDARDS.md plus a per-institution badge.

Tiers are derived entirely from what's already checked into resources/.
Nothing here is assigned manually, so a maintainer who adds one course.yml
watches their tier rise on the next merge.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import click

from . import model as m

MIN_SUMMARY_LEN = 40  # heuristic floor for a README first paragraph to count as "documented"
BADGES_DIR_NAME = "badges"

TIER_ORDER = {"Pooled": 4, "Documented": 3, "Structured": 2, "Listed": 1, "Unlisted": 0}
TIER_BADGE = {
    "Pooled": "🥇 Pooled",
    "Documented": "🥈 Documented",
    "Structured": "🥉 Structured",
    "Listed": "⬜ Listed",
    "Unlisted": "❔ Unlisted",
}
TIER_COLOR = {
    "Pooled": "gold",
    "Documented": "blue",
    "Structured": "orange",
    "Listed": "lightgrey",
    "Unlisted": "red",
}

HEADER = """# Compliance scorecard

Every institution directory earns a tier automatically from what it has
adopted; nothing here is assigned by hand. Generated by
`tools/scorecard.py`; see `CONTRIBUTING.md` for how to move up a tier.

| Tier | Requirement |
|---|---|
| ⬜ Listed | Directory name is registered in `institutions.yml`. |
| 🥉 Structured | `resource.yml` and every `course.yml` are present and valid. |
| 🥈 Documented | The institution and every course have a substantive `README.md`. |
| 🥇 Pooled | At least one asset is admitted into `common/`. |
"""


def _substantive(summary: str | None) -> bool:
    return bool(summary) and len(summary) >= MIN_SUMMARY_LEN


def tier_for(root: Path, resource: m.Resource, institutions: dict[str, m.Institution]) -> str:
    if resource.slug not in institutions:
        return "Unlisted"

    has_resource_yml = (root / resource.path / "resource.yml").exists()
    has_all_course_ymls = bool(resource.courses) and all(
        (root / c.path / "course.yml").exists() for c in resource.courses
    )
    structured = has_resource_yml and has_all_course_ymls

    documented = (
        structured
        and _substantive(resource.readme_summary)
        and all(_substantive(c.readme_summary) for c in resource.courses)
    )

    pooled = any(a.pooled for c in resource.courses for a in c.assets)

    if pooled and documented:
        return "Pooled"
    if documented:
        return "Documented"
    if structured:
        return "Structured"
    return "Listed"


def render(root: Path, repo: m.RepoModel) -> str:
    rows = []
    for resource in repo.resources:
        tier = tier_for(root, resource, repo.institutions)
        pooled_count = sum(1 for c in resource.courses for a in c.assets if a.pooled)
        institution = repo.institutions.get(resource.slug)
        name = institution.name if institution else resource.slug
        rows.append((tier, name, resource.slug, len(resource.courses), pooled_count))

    rows.sort(key=lambda r: (-TIER_ORDER[r[0]], r[1]))

    lines = [HEADER, "| Institution | Tier | Courses | Pooled assets |", "|---|---|---|---|"]
    if not rows:
        lines.append("| _none yet_ | | | |")
    for tier, name, slug, n_courses, n_pooled in rows:
        lines.append(f"| [{name}](resources/{slug}) | {TIER_BADGE[tier]} | {n_courses} | {n_pooled} |")

    return "\n".join(lines) + "\n"


def _badge_json(tier: str) -> dict:
    return {
        "schemaVersion": 1,
        "label": "rvi-education-central",
        "message": TIER_BADGE[tier],
        "color": TIER_COLOR[tier],
    }


def build(root: Path) -> None:
    repo = m.load(root)
    (root / "STANDARDS.md").write_text(render(root, repo), encoding="utf-8")

    # badges/ is bot-owned, like common/: wipe and regenerate every run so resources/
    # stays entirely static and user-defined.
    badges_dir = root / BADGES_DIR_NAME
    if badges_dir.exists():
        for path in badges_dir.iterdir():
            if path.suffix != ".json":
                raise SystemExit(
                    f"{path.relative_to(root)} is not a generated badge; refusing to wipe {BADGES_DIR_NAME}/"
                )
        shutil.rmtree(badges_dir)
    badges_dir.mkdir(parents=True)

    for resource in repo.resources:
        tier = tier_for(root, resource, repo.institutions)
        badge_path = badges_dir / f"{resource.slug}.json"
        badge_path.write_text(json.dumps(_badge_json(tier), indent=2, sort_keys=True) + "\n", encoding="utf-8")


@click.command()
@click.argument("root", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
def main(root: Path) -> None:
    build(m.find_repo_root(root))
    click.echo("STANDARDS.md and badge.json files regenerated")


if __name__ == "__main__":
    main()
