"""Structural, schema, and naming validation. The only required CI check.

Runs identically locally (`python -m tools.validate .` or `uv run --project
tools python -m tools.cli check .`) and in the validate.yml workflow, so a
contributor can reproduce a CI failure before opening a pull request.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import click
import jsonschema
import yaml

from . import model as m

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"


def _schema(name: str) -> dict:
    with (SCHEMA_DIR / name).open("r", encoding="utf-8") as f:
        return json.load(f)


def _check_schema(raw: object, schema: dict, label: str, errors: list[str]) -> None:
    validator = jsonschema.Draft202012Validator(schema)
    for e in validator.iter_errors(raw):
        location = "/".join(str(p) for p in e.absolute_path)
        where = f"{label}:{location}" if location else label
        errors.append(f"{where}: {e.message}")


def validate_repo(root: Path) -> list[str]:
    """Return human-readable error strings; an empty list means the repo is clean."""
    errors: list[str] = []

    institution_schema = _schema("institution.schema.json")
    resource_schema = _schema("resource.schema.json")
    course_schema = _schema("course.schema.json")
    asset_meta_schema = _schema("asset-meta.schema.json")

    repo = m.load(root)
    errors.extend(str(e) for e in repo.errors)

    institutions_path = root / "institutions.yml"
    if institutions_path.exists():
        raw_institutions = yaml.safe_load(institutions_path.read_text(encoding="utf-8")) or {}
        if isinstance(raw_institutions, dict):
            for slug, entry in raw_institutions.items():
                _check_schema(entry, institution_schema, f"institutions.yml[{slug}]", errors)

    for resource in repo.resources:
        resource_yml = root / resource.path / "resource.yml"
        if resource_yml.exists():
            raw = yaml.safe_load(resource_yml.read_text(encoding="utf-8")) or {}
            _check_schema(raw, resource_schema, str(resource_yml.relative_to(root)), errors)

        for course in resource.courses:
            course_yml = root / course.path / "course.yml"
            raw = yaml.safe_load(course_yml.read_text(encoding="utf-8")) or {}
            _check_schema(raw, course_schema, str(course_yml.relative_to(root)), errors)

            for asset in course.assets:
                meta_path = root / asset.path.with_name(asset.path.name + m.ASSET_META_SUFFIX)
                if meta_path.exists():
                    raw_meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
                    _check_schema(raw_meta, asset_meta_schema, str(meta_path.relative_to(root)), errors)

    # common/ is bot-owned; reject anything that isn't a generated symlink or gallery README.
    common_dir = root / "common"
    if common_dir.is_dir():
        for path in common_dir.rglob("*"):
            if path.is_file() and not path.is_symlink() and path.name != "README.md":
                errors.append(
                    f"{path.relative_to(root)}: common/ is generated by tools/build_common.py; "
                    "only symlinks and generated gallery README.md files belong here"
                )

    # Every .gitmodules entry must resolve to a directory that actually exists once checked out.
    for sub_path in repo.gitmodules:
        if not (root / sub_path).is_dir():
            errors.append(f".gitmodules: submodule path '{sub_path}' is missing from the working tree")

    return errors


@click.command()
@click.argument("root", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
def main(root: Path) -> None:
    errors = validate_repo(m.find_repo_root(root))
    if errors:
        for e in errors:
            click.echo(e, err=True)
        click.echo(f"\n{len(errors)} error(s).", err=True)
        sys.exit(1)
    click.echo("ok")


if __name__ == "__main__":
    main()
